spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  session:
    timeout: 2592000

server:
  servlet:
    context-path: /api
    session:
      cookie:
        # cookie过期时间 30天
        max-age: 2592000  # 30 * 24 * 60 * 60